CREATE TABLE [dbo].[Product]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Price] FLOAT NOT NULL, 
    [ShopId] UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY ([ShopId]) REFERENCES Shop(Id)
)
